package cfggen

var configTemplate = `// Code generated by "gogen cfggen"; DO NOT EDIT.
// Exec: gogen {{.Commands}} Version: {{.Version}}
package {{.PackageName}}

import (
    "time"
    "github.com/spf13/viper"
    "github.com/walleframe/walle/services/configcentra"
)

var _ = {{.FromFunc}}()

// {{.Name}} config generate by gogen cfggen.
type {{.Name}} struct { {{- range $i,$f := .Fields }}
    {{Comment $f -}}
    {{$f.Name}} {{$f.Type}} {{- end }}
    // config prefix string
    prefix string
    // update ntf funcs
    ntfFuncs []func(*{{.Name}})
}

var _ configcentra.ConfigValue = (*{{.Name}})(nil)

func New{{.Name}}(prefix string) *{{.Name}}{
    // new default config value
    cfg := NewDefault{{.Name}}(prefix)
    // register value to config centra
    configcentra.RegisterConfig(cfg)
    return cfg
}

func NewDefault{{.Name}}(prefix string)*{{.Name}}{
    cfg := &{{.Name -}} { {{- range $i,$f := .Fields}}
        {{$f.Name}} : {{$f.Body}}, {{- end}}
        prefix : prefix,
    }
    return cfg
}

// add notify func
func (cfg *{{.Name}}) AddNotifyFunc(f func(*{{.Name}})) {
    cfg.ntfFuncs = append(cfg.ntfFuncs, f)
}

// impl configcentra.ConfigValue
func (cfg *{{.Name}}) SetDefaultValue(cc configcentra.ConfigCentra) {
    if cfg.prefix == "" {  {{- range $i,$f := .Fields}}
        cc.SetDefault("{{ToLower $f.Name}}", "{{$f.Doc}}", cfg.{{$f.Name}}) {{- end }}
    } else { {{- range $i,$f := .Fields}}
        cc.SetDefault(cfg.prefix + ".{{ToLower $f.Name}}", "{{$f.Doc}}", cfg.{{$f.Name}}) {{- end }}
    } 
}

// impl configcentra.ConfigValue
func (cfg *{{.Name}}) RefreshValue(cc configcentra.ConfigCentra) {
    if cfg.prefix == "" {  {{- range $i,$f := .Fields}}
        cfg.{{$f.Name}} = ({{$f.Type}})(cc.{{$f.GetMethod}}("{{ToLower $f.Name}}")) {{- end }}
    } else { {{- range $i,$f := .Fields}}
        cfg.{{$f.Name}} = ({{$f.Type}})(cc.{{$f.GetMethod}}(cfg.prefix + ".{{ToLower $f.Name}}")) {{- end }}
    }
    // notify update
    for _, ntf := range cfg.ntfFuncs {
        ntf(cfg)
    }
}
`
