// Code generated by "gogen import"; DO NOT EDIT.
// Exec: "gogen import ./testdata -t TestType -t TestString -o gen_td.go"
// Version: 0.0.2

package sample

import testdata "github.com/aggronmagi/gogen/samples/testdata"

// TestType test type comment 1
// second line comment
type TestType = testdata.TestType //  comment 2

const (
	// T1 comment 11
	T1 = testdata.T1 // line suffix comment 1
	// T2 comment 22
	T2 = testdata.T2
	T3 = testdata.T3 // T3 line suffix comment 1
)

// NewTestType new func 1
var NewTestType = testdata.NewTestType

// NewTestType2 new func 2
var NewTestType2 = testdata.NewTestType2

// TestString comment for test string 1
type TestString = testdata.TestString //  comment for test string 2
